#Server Information
  DEVELOPMENT:
    serverInfo: 
        applicationName: AZURIAN BOT
        appVersion: 1.0.0 
        instanceName: 
        port: 8083 
        corsHeaders: ["Link"]
        publishHost: https://zany-gold-scorpion-garb.cyclic.app
    botConfig:
        token: 2123471074:AAGQ6KhF0u8 # 2123471074:AAGQ6KhF0u8 6190170452:AAHHwntNDDA
        name: Edu Bot(Dev) # Dev_AIHSP_Bot
        hookPath: /hook
        renderImage: true
        defaultLanguage: id
        secondVerse: ZzvEiUH4t4Aj8KwVTR7nNYe0 # ZzvEiUH4t4Aj8KwVTR7nNYe0 YyabVU7uGopoCQCn7YgjvcfQ